# Generated by Django 3.0.8 on 2020-07-17 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200717_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='Order',
        ),
    ]
