# Generated by Django 3.0.8 on 2020-07-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200720_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='datestamp',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orderupdate',
            name='timestamp',
            field=models.TimeField(auto_now=True),
        ),
    ]
