# Generated by Django 3.0.8 on 2020-07-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20200720_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='datestamp',
            field=models.DateField(auto_now=True),
        ),
    ]
