# Generated by Django 3.0.8 on 2020-08-22 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200822_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='datestamp',
        ),
    ]
