# Generated by Django 3.0.8 on 2020-08-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_orderupdate_datestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='orderupdate',
            name='datestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
