# Generated by Django 3.0.8 on 2020-08-22 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20200822_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='datestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
